### ISSUE TITLE
Random 500 error 

### ISSUE THREAD

**Issue by chunyihh** [adzerk/adzerk-decision-sdk-ruby#7]
The server sometimes returns a 500 error when making decisions request using the SDK. I got:

`AdzerkDecisionSdk::ApiError:
Error message: the server returns an error
HTTP status code: 500
Response headers: {"Date"=>"Wed, 05 Aug 2020 16:07:53 GMT", "Content-Type"=>"text/html; charset=utf-8", "Content-Length"=>"21", "Connection"=>"keep-alive", "Server"=>"nginx/1.16.1", "x-powered-by"=>"adzerk bifrost/", "Access-Control-Allow-Origin"=>"undefined", "Access-Control-Allow-Credentials"=>"true", "Access-Control-Allow-Methods"=>"GET, PUT, POST, DELETE, OPTIONS", "Access-Control-Allow-Headers"=>"Accept, Origin, Content-Type, Content-Length, X-Adzerk-Explain, X-Adzerk-Sdk-Version", "Cache-Control"=>"no-cache, no-store, must-revalidate", "Expires"=>"0", "Pragma"=>"no-cache", "x-served-by"=>"engine-i-0c52437cae620a286", "ETag"=>"W/\"15-/6VXivhc2MKdLfIkLcUE47K6aH0\""}
Response body: Internal Server Error
(Most recent call first)`

This is how I make the call:
`AdzerkDecisionSdk::Client.new(network_id: 11111, site_id: 22222).decisions.get(build_request(placements, site_id, user_id, **kargs))`

The build_request method constructs a request object like this: 
`{:placements=>[{:divName=>"div1", :adTypes=>[4], :properties=>{:brandNames=>["AAA", "BBB", "CCC"]}, :networkId=>11111, :siteId=>22222, :zoneIds=>[33333]}, {:divName=>"div2", :adTypes=>[1578], :properties=>{:brandNames=>["AAA", "BBB", "CCC"]}, :networkId=>11111, :siteId=>22222, :zoneIds=>[33333]}], :user=>{:key=>"28"}}`

I'm using a Network Zone in this case. Any idea what's wrong? 

Thanks!

**Comment by karnowski** [comment]
Note that Adzerk is working with @chunyihh using the support process.  (I just forgot to add a comment here making it obvious.)

**Comment by karnowski** [comment]
We're pretty sure this is not a Ruby SDK error, and so I'm closing this issue.
